### ISSUE TITLE
Add marker on map for single destination

### ISSUE THREAD

**Issue by derjubu** [derjubu/capstone-project#16]
_As a_ user
_I want to_ see a pin on a map, when I enter a destination
_in order to_ get a better overview of my trip
---
## Description
![image](https://user-images.githubusercontent.com/91471701/144035230-895ed5b6-8413-40f4-923a-a3508c79bce1.png)

![image](https://user-images.githubusercontent.com/91471701/144035570-886f11f4-f1f2-441a-b24b-ead88f445c23.png)

--
## Acceptance Criteria

- [x] Autofill works
- [x] Marker on Map is shown
- [x] Map in implemented in AddDestination
- [x] Map in implemented in DestinationDetailview

## Tasks

- [x] Read Doc for Marker
- [x] Implement Searchfield on Map
- [x] Implement Autofill on Searchfield
- [x] Show Marker on Map
- [x] Transfer solution to AddDestination
- [x] Transfer solution to DestinationDetailView
