### ISSUE TITLE
Show itinerary in Itinerary.tsx

### ISSUE THREAD

**Issue by derjubu** [derjubu/capstone-project#17]
**As a** user
**I need** to see a route
**to be able to** get an impression of my trip
---
## Description
---
## Acceptance Criteria
---
- [x] Shown map an Itinerary
- [x] For each entry in itinerary, show a marke on map
- [x] Connect all markers regarding to their index in itinerary

## Tasks

- [x] Shown map on Itinerary, if there are entries
- [x] Set markers for all entries
- [x] Connect all markers
