### ISSUE TITLE
Add destination function

### ISSUE THREAD

**Issue by derjubu** [derjubu/capstone-project#2]
**As a** user
**I need** an input for my destination
**to be able to** make a waypoint for my route
## Description
![142846828-67a0cbae-6da4-4c4b-9037-ffa15e6324be](https://user-images.githubusercontent.com/91471701/143429133-3e34b6b2-c8dc-4ad9-a2db-895941184185.png)
UPDATE: Tasklist has been taken from this issue and outsourced into another issue (#9 ).
## Acceptance Criteria
- [x] Form with the following information: Location (required), period of stay, ~~notes on stay~~ OUTDATED
- [x] After submitting the form, the information need to be displayed as an overview page
## Tasks
- [x] Create text input for location
- [x] Create date input for period of stay
~~Create tasklist~~ OUTDATED
- [x] Input gets saved in array
- [x] Create detailviewpage
