### ISSUE TITLE
Add mongoDB

### ISSUE THREAD

**Issue by derjubu** [derjubu/capstone-project#23]
As a user I want to store my data so I can access them from everywhere.

---
##Description

Save the data in a mongoDB and create individual IDs for each trip.

---
##Tasks

- [x] Setup mongoDB (incl. data structure)
- [x] Integrate random ID for each trip
- [x] Save data to mongoDB 
- [x] Make data from mongoDB accessible
- [x] Allow data to be deleted

**Comment by derjubu** [comment]
All tasks completed
