### ISSUE TITLE
Add itinerary

### ISSUE THREAD

**Issue by derjubu** [derjubu/capstone-project#3]
**As a** user
**I need** an overview of my waypoints
**to be able to** see my travelroute
---
## Description
![image](https://user-images.githubusercontent.com/91471701/142848976-1689075b-933a-4cb9-a8ff-c617a19a1937.png)

---
## Acceptance Criteria
- [x] All stops added so far are shown
- [x] On click of a destination, you get to the detailview of the stop (#2 )
- [x] Button to add new stop
- [x] Button to go back from detailview to overview

---
## Tasks
- [x] Create array for all stops
- [x] Show location and period in overview
- [x] Button to open form to add another destination (#2 )
- [x] Button to go back to overview
