### ISSUE TITLE
Implement 'Edit' function

### ISSUE THREAD

**Issue by derjubu** [derjubu/capstone-project#33]
### Userstor
As a user I want to change the data on single stops if I made a mistake

### Description
Add an edit function to each stop

### Tasks
- [x] Implement mongoDB update function
- [x] Implement Update route in browser routing
- [x] Implement Edit-Page
