### ISSUE TITLE
Initial Figma design

### ISSUE THREAD

**Issue by derjubu** [derjubu/capstone-project#6]
**As a** developer
**I need** an app design
**to be able to** create the desired components
## Description
Create a design in Figma for TravelBuddy
## Acceptance Criteria
- [ ] Form to add new destinations (Location, period, tasklist)
- [ ] Detailview for each destination
- [ ] Overview over whole trip (entry for each destination, button to add new destination)
## Tasks
- [ ] Create Figma file for the features mentioned above
